language: python

python:
  - 3.4

install: pip install -r scripts/requirements.txt
script: python test/workout.py

after_success: pyflakes scripts/*.py

notifications:
  email:
    recipients:
      - eric@sunlightfoundation.com
      - tauberer@govtrack.us
    on_success: change
    on_failure: change
